repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: check-docstring-first
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: check-json
    -   id: check-toml
    -   id: check-shebang-scripts-are-executable
    -   id: check-illegal-windows-names
    -   id: name-tests-test
        args: [ --pytest-test-first ]
        exclude: ^tests/utils.py$

  # Ensure uv.lock file is up to date even if pyproject.toml file was changed via pre-commit
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.7.6
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.10
    hooks:
      # Run the linter and try to fix any errors.
      - id: ruff
        args: [ --fix ]
        types_or: [ python ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python ]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3
    hooks:
      - id: bandit

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.16.0'
    hooks:
        - id: mypy
          exclude: ^tests/   # we do not care about tests
          args: [--strict, --ignore-missing-imports, --check-untyped-defs]
          language: system  # make mypy use the same env as pre-commit
          types_or: [ python, pyi ]